spring.application.name=reserva-cine-api

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/reserva_cine_db?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD

# JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Properties
jwt.secret=TU_CLAVE_SECRETA_JWT
jwt.expiration=86400000

# Server
server.port=8086

# Logging
logging.level.org.springframework.security=DEBUG